import Config

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :esther_pictures, EstherPicturesWeb.Endpoint,
  cache_static_manifest: "priv/static/cache_manifest.json",
  # LiveView's websocket accepts both names the site is served on. Host only
  # ("//"): TLS ends at Cloudflare, so the app sees http on its own port while
  # browsers send https origins (check_origin: :conn would refuse them all).
  check_origin: ["//estherpictures.com", "//estherpictures.svnmns.com"]

# User uploads live on the VM's persistent data volume, outside the release
# directory, so they survive deploys. The deploy setup creates this path.
config :esther_pictures, EstherPictures.Uploads, root: "/opt/estherpictures/data/uploads"

# TLS is terminated at Cloudflare (tunnel/orange-cloud). Origin traffic is plain
# HTTP to Traefik, so X-Forwarded-Proto is often "http". Phoenix `force_ssl`
# would then 301→https forever (redirect loop). Keep HTTPS enforcement on CF
# ("Always Use HTTPS" / HSTS); do not force_ssl at the app.

# Configure Swoosh API Client
config :swoosh, api_client: Swoosh.ApiClient.Req

# Disable Swoosh Local Memory Storage
config :swoosh, local: false

# Do not print debug messages in production
config :logger, level: :info

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
