defmodule EstherPicturesWeb.Endpoint do
  use Phoenix.Endpoint, otp_app: :esther_pictures

  # The session will be stored in the cookie and signed,
  # this means its contents can be read but not tampered with.
  # Set :encryption_salt if you would also like to encrypt it.
  @session_options [
    store: :cookie,
    key: "_esther_pictures_key",
    signing_salt: "eB8bopHQ",
    same_site: "Lax"
  ]

  socket "/live", Phoenix.LiveView.Socket,
    websocket: [connect_info: [session: @session_options]],
    longpoll: [connect_info: [session: @session_options]]

  # /up answers 200 on any host, first: Houston's health check before it
  # switches traffic to a new version.
  plug EstherPicturesWeb.Plugs.Health

  # Redirect www.* to the bare apex host (canonical URL) before anything else.
  plug EstherPicturesWeb.Plugs.CanonicalHost

  # Serve at "/" the static files from "priv/static" directory.
  #
  # When code reloading is disabled (e.g., in production),
  # the `gzip` option is enabled to serve compressed
  # static files generated by running `phx.digest`.
  plug Plug.Static,
    at: "/",
    from: :esther_pictures,
    gzip: not code_reloading?,
    only: EstherPicturesWeb.static_paths(),
    raise_on_missing_only: code_reloading?

  # User-uploaded files (clip thumbnails) live outside the release so they
  # survive deploys. The directory is configured per-env via
  # `config :esther_pictures, EstherPictures.Uploads, root: ...`
  # (priv/static/uploads in dev; a persistent path in prod).
  plug Plug.Static,
    at: "/uploads",
    from: Application.compile_env(:esther_pictures, [EstherPictures.Uploads, :root]),
    gzip: false

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    socket "/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket
    plug Phoenix.LiveReloader
    plug Phoenix.CodeReloader
    plug Phoenix.Ecto.CheckRepoStatus, otp_app: :esther_pictures
  end

  plug Phoenix.LiveDashboard.RequestLogger,
    param_key: "request_logger",
    cookie_key: "request_logger"

  plug Plug.RequestId
  plug Plug.Telemetry, event_prefix: [:phoenix, :endpoint]

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Phoenix.json_library()

  plug Plug.MethodOverride
  plug Plug.Head
  plug Plug.Session, @session_options
  plug EstherPicturesWeb.Router
end
