// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: clips.sql

package models

import (
	"context"
)

const clearClipUpload = `-- name: ClearClipUpload :exec
UPDATE clips SET thumbnail_path = '' WHERE id = ?
`

func (q *Queries) ClearClipUpload(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, clearClipUpload, id)
	return err
}

const countClips = `-- name: CountClips :one
SELECT count(*) FROM clips
`

func (q *Queries) CountClips(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countClips)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createClip = `-- name: CreateClip :one
INSERT INTO clips (position, title, video_url, runtime, format, years, status, created_at, updated_at)
VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8, ?8)
RETURNING id
`

type CreateClipParams struct {
	Position int64
	Title    string
	VideoUrl string
	Runtime  string
	Format   string
	Years    string
	Status   string
	Now      string
}

func (q *Queries) CreateClip(ctx context.Context, arg CreateClipParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, createClip,
		arg.Position,
		arg.Title,
		arg.VideoUrl,
		arg.Runtime,
		arg.Format,
		arg.Years,
		arg.Status,
		arg.Now,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const deleteClip = `-- name: DeleteClip :exec
DELETE FROM clips WHERE id = ?
`

func (q *Queries) DeleteClip(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteClip, id)
	return err
}

const getClip = `-- name: GetClip :one
SELECT id, position, title, created_at, updated_at, video_url, thumbnail_path, runtime, format, years, status FROM clips WHERE id = ?
`

func (q *Queries) GetClip(ctx context.Context, id int64) (Clip, error) {
	row := q.db.QueryRowContext(ctx, getClip, id)
	var i Clip
	err := row.Scan(
		&i.ID,
		&i.Position,
		&i.Title,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.VideoUrl,
		&i.ThumbnailPath,
		&i.Runtime,
		&i.Format,
		&i.Years,
		&i.Status,
	)
	return i, err
}

const listClipUploads = `-- name: ListClipUploads :many

SELECT id, thumbnail_path FROM clips WHERE thumbnail_path <> ''
`

type ListClipUploadsRow struct {
	ID            int64
	ThumbnailPath string
}

// Phoenix's thumbnails, for moving them into storage: gone once moved.
func (q *Queries) ListClipUploads(ctx context.Context) ([]ListClipUploadsRow, error) {
	rows, err := q.db.QueryContext(ctx, listClipUploads)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListClipUploadsRow{}
	for rows.Next() {
		var i ListClipUploadsRow
		if err := rows.Scan(&i.ID, &i.ThumbnailPath); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listClips = `-- name: ListClips :many
SELECT id, position, title, created_at, updated_at, video_url, thumbnail_path, runtime, format, years, status FROM clips ORDER BY position, id
`

func (q *Queries) ListClips(ctx context.Context) ([]Clip, error) {
	rows, err := q.db.QueryContext(ctx, listClips)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Clip{}
	for rows.Next() {
		var i Clip
		if err := rows.Scan(
			&i.ID,
			&i.Position,
			&i.Title,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.VideoUrl,
			&i.ThumbnailPath,
			&i.Runtime,
			&i.Format,
			&i.Years,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const restoreClip = `-- name: RestoreClip :exec
INSERT INTO clips (id, position, title, video_url, runtime, format, years, status, created_at, updated_at)
VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8, ?9, ?9)
`

type RestoreClipParams struct {
	ID       int64
	Position int64
	Title    string
	VideoUrl string
	Runtime  string
	Format   string
	Years    string
	Status   string
	Now      string
}

func (q *Queries) RestoreClip(ctx context.Context, arg RestoreClipParams) error {
	_, err := q.db.ExecContext(ctx, restoreClip,
		arg.ID,
		arg.Position,
		arg.Title,
		arg.VideoUrl,
		arg.Runtime,
		arg.Format,
		arg.Years,
		arg.Status,
		arg.Now,
	)
	return err
}

const updateClip = `-- name: UpdateClip :exec
UPDATE clips SET position = ?1, title = ?2, video_url = ?3, runtime = ?4, format = ?5,
  years = ?6, status = ?7, updated_at = ?8
WHERE id = ?9
`

type UpdateClipParams struct {
	Position int64
	Title    string
	VideoUrl string
	Runtime  string
	Format   string
	Years    string
	Status   string
	Now      string
	ID       int64
}

func (q *Queries) UpdateClip(ctx context.Context, arg UpdateClipParams) error {
	_, err := q.db.ExecContext(ctx, updateClip,
		arg.Position,
		arg.Title,
		arg.VideoUrl,
		arg.Runtime,
		arg.Format,
		arg.Years,
		arg.Status,
		arg.Now,
		arg.ID,
	)
	return err
}
