// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: content_versions.sql

package models

import (
	"context"
	"database/sql"
)

const createContentVersion = `-- name: CreateContentVersion :exec
INSERT INTO content_versions (item_type, item_id, action, data, user_id, created_at)
VALUES (?1, ?2, ?3, ?4, ?5, ?6)
`

type CreateContentVersionParams struct {
	ItemType string
	ItemID   int64
	Action   string
	Data     string
	UserID   sql.NullInt64
	Now      string
}

func (q *Queries) CreateContentVersion(ctx context.Context, arg CreateContentVersionParams) error {
	_, err := q.db.ExecContext(ctx, createContentVersion,
		arg.ItemType,
		arg.ItemID,
		arg.Action,
		arg.Data,
		arg.UserID,
		arg.Now,
	)
	return err
}

const deleteContentVersion = `-- name: DeleteContentVersion :exec
DELETE FROM content_versions WHERE id = ?
`

func (q *Queries) DeleteContentVersion(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteContentVersion, id)
	return err
}

const deleteContentVersions = `-- name: DeleteContentVersions :execrows
DELETE FROM content_versions
`

func (q *Queries) DeleteContentVersions(ctx context.Context) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteContentVersions)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getContentVersion = `-- name: GetContentVersion :one
SELECT id, item_type, item_id, "action", data, user_id, created_at FROM content_versions WHERE id = ?
`

func (q *Queries) GetContentVersion(ctx context.Context, id int64) (ContentVersion, error) {
	row := q.db.QueryRowContext(ctx, getContentVersion, id)
	var i ContentVersion
	err := row.Scan(
		&i.ID,
		&i.ItemType,
		&i.ItemID,
		&i.Action,
		&i.Data,
		&i.UserID,
		&i.CreatedAt,
	)
	return i, err
}

const listContentVersionData = `-- name: ListContentVersionData :many
SELECT id, item_type, data FROM content_versions
`

type ListContentVersionDataRow struct {
	ID       int64
	ItemType string
	Data     string
}

func (q *Queries) ListContentVersionData(ctx context.Context) ([]ListContentVersionDataRow, error) {
	rows, err := q.db.QueryContext(ctx, listContentVersionData)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListContentVersionDataRow{}
	for rows.Next() {
		var i ListContentVersionDataRow
		if err := rows.Scan(&i.ID, &i.ItemType, &i.Data); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listContentVersionIDs = `-- name: ListContentVersionIDs :many
SELECT id FROM content_versions WHERE item_type = ? AND item_id = ? ORDER BY created_at DESC, id DESC
`

type ListContentVersionIDsParams struct {
	ItemType string
	ItemID   int64
}

func (q *Queries) ListContentVersionIDs(ctx context.Context, arg ListContentVersionIDsParams) ([]int64, error) {
	rows, err := q.db.QueryContext(ctx, listContentVersionIDs, arg.ItemType, arg.ItemID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listContentVersions = `-- name: ListContentVersions :many
SELECT v.id, v.item_type, v.item_id, v.action, v.data, v.created_at, COALESCE(u.email_address, '') AS email_address
FROM content_versions v LEFT JOIN users u ON u.id = v.user_id
ORDER BY v.created_at DESC, v.id DESC
LIMIT ?
`

type ListContentVersionsRow struct {
	ID           int64
	ItemType     string
	ItemID       int64
	Action       string
	Data         string
	CreatedAt    string
	EmailAddress string
}

func (q *Queries) ListContentVersions(ctx context.Context, limit int64) ([]ListContentVersionsRow, error) {
	rows, err := q.db.QueryContext(ctx, listContentVersions, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListContentVersionsRow{}
	for rows.Next() {
		var i ListContentVersionsRow
		if err := rows.Scan(
			&i.ID,
			&i.ItemType,
			&i.ItemID,
			&i.Action,
			&i.Data,
			&i.CreatedAt,
			&i.EmailAddress,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateContentVersionData = `-- name: UpdateContentVersionData :exec
UPDATE content_versions SET data = ? WHERE id = ?
`

type UpdateContentVersionDataParams struct {
	Data string
	ID   int64
}

func (q *Queries) UpdateContentVersionData(ctx context.Context, arg UpdateContentVersionDataParams) error {
	_, err := q.db.ExecContext(ctx, updateContentVersionData, arg.Data, arg.ID)
	return err
}
