// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: craft_services.sql

package models

import (
	"context"
)

const countCraftServices = `-- name: CountCraftServices :one
SELECT count(*) FROM craft_services
`

func (q *Queries) CountCraftServices(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countCraftServices)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createCraftService = `-- name: CreateCraftService :one
INSERT INTO craft_services (position, title, description, created_at, updated_at) VALUES (?1, ?2, ?3, ?4, ?4)
RETURNING id
`

type CreateCraftServiceParams struct {
	Position    int64
	Title       string
	Description string
	Now         string
}

func (q *Queries) CreateCraftService(ctx context.Context, arg CreateCraftServiceParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, createCraftService,
		arg.Position,
		arg.Title,
		arg.Description,
		arg.Now,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const deleteCraftService = `-- name: DeleteCraftService :exec
DELETE FROM craft_services WHERE id = ?
`

func (q *Queries) DeleteCraftService(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteCraftService, id)
	return err
}

const getCraftService = `-- name: GetCraftService :one
SELECT id, position, title, description, created_at, updated_at FROM craft_services WHERE id = ?
`

func (q *Queries) GetCraftService(ctx context.Context, id int64) (CraftService, error) {
	row := q.db.QueryRowContext(ctx, getCraftService, id)
	var i CraftService
	err := row.Scan(
		&i.ID,
		&i.Position,
		&i.Title,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCraftServices = `-- name: ListCraftServices :many
SELECT id, position, title, description, created_at, updated_at FROM craft_services ORDER BY position, id
`

func (q *Queries) ListCraftServices(ctx context.Context) ([]CraftService, error) {
	rows, err := q.db.QueryContext(ctx, listCraftServices)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CraftService{}
	for rows.Next() {
		var i CraftService
		if err := rows.Scan(
			&i.ID,
			&i.Position,
			&i.Title,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const restoreCraftService = `-- name: RestoreCraftService :exec
INSERT INTO craft_services (id, position, title, description, created_at, updated_at) VALUES (?1, ?2, ?3, ?4, ?5, ?5)
`

type RestoreCraftServiceParams struct {
	ID          int64
	Position    int64
	Title       string
	Description string
	Now         string
}

func (q *Queries) RestoreCraftService(ctx context.Context, arg RestoreCraftServiceParams) error {
	_, err := q.db.ExecContext(ctx, restoreCraftService,
		arg.ID,
		arg.Position,
		arg.Title,
		arg.Description,
		arg.Now,
	)
	return err
}

const updateCraftService = `-- name: UpdateCraftService :exec
UPDATE craft_services SET position = ?1, title = ?2, description = ?3, updated_at = ?4 WHERE id = ?5
`

type UpdateCraftServiceParams struct {
	Position    int64
	Title       string
	Description string
	Now         string
	ID          int64
}

func (q *Queries) UpdateCraftService(ctx context.Context, arg UpdateCraftServiceParams) error {
	_, err := q.db.ExecContext(ctx, updateCraftService,
		arg.Position,
		arg.Title,
		arg.Description,
		arg.Now,
		arg.ID,
	)
	return err
}
