// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ensemble_members.sql

package models

import (
	"context"
)

const clearEnsembleMemberUpload = `-- name: ClearEnsembleMemberUpload :exec
UPDATE ensemble_members SET headshot_path = '' WHERE id = ?
`

func (q *Queries) ClearEnsembleMemberUpload(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, clearEnsembleMemberUpload, id)
	return err
}

const countEnsembleMembers = `-- name: CountEnsembleMembers :one
SELECT count(*) FROM ensemble_members
`

func (q *Queries) CountEnsembleMembers(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countEnsembleMembers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createEnsembleMember = `-- name: CreateEnsembleMember :one
INSERT INTO ensemble_members (position, name, role, since_year, bio, created_at, updated_at)
VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?6)
RETURNING id
`

type CreateEnsembleMemberParams struct {
	Position  int64
	Name      string
	Role      string
	SinceYear string
	Bio       string
	Now       string
}

func (q *Queries) CreateEnsembleMember(ctx context.Context, arg CreateEnsembleMemberParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, createEnsembleMember,
		arg.Position,
		arg.Name,
		arg.Role,
		arg.SinceYear,
		arg.Bio,
		arg.Now,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const deleteEnsembleMember = `-- name: DeleteEnsembleMember :exec
DELETE FROM ensemble_members WHERE id = ?
`

func (q *Queries) DeleteEnsembleMember(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteEnsembleMember, id)
	return err
}

const getEnsembleMember = `-- name: GetEnsembleMember :one
SELECT id, position, name, role, since_year, created_at, updated_at, bio, headshot_path FROM ensemble_members WHERE id = ?
`

func (q *Queries) GetEnsembleMember(ctx context.Context, id int64) (EnsembleMember, error) {
	row := q.db.QueryRowContext(ctx, getEnsembleMember, id)
	var i EnsembleMember
	err := row.Scan(
		&i.ID,
		&i.Position,
		&i.Name,
		&i.Role,
		&i.SinceYear,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Bio,
		&i.HeadshotPath,
	)
	return i, err
}

const listEnsembleMemberUploads = `-- name: ListEnsembleMemberUploads :many

SELECT id, headshot_path FROM ensemble_members WHERE headshot_path <> ''
`

type ListEnsembleMemberUploadsRow struct {
	ID           int64
	HeadshotPath string
}

// Phoenix's headshots, for moving them into storage: gone once moved.
func (q *Queries) ListEnsembleMemberUploads(ctx context.Context) ([]ListEnsembleMemberUploadsRow, error) {
	rows, err := q.db.QueryContext(ctx, listEnsembleMemberUploads)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEnsembleMemberUploadsRow{}
	for rows.Next() {
		var i ListEnsembleMemberUploadsRow
		if err := rows.Scan(&i.ID, &i.HeadshotPath); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEnsembleMembers = `-- name: ListEnsembleMembers :many
SELECT id, position, name, role, since_year, created_at, updated_at, bio, headshot_path FROM ensemble_members ORDER BY position, id
`

func (q *Queries) ListEnsembleMembers(ctx context.Context) ([]EnsembleMember, error) {
	rows, err := q.db.QueryContext(ctx, listEnsembleMembers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EnsembleMember{}
	for rows.Next() {
		var i EnsembleMember
		if err := rows.Scan(
			&i.ID,
			&i.Position,
			&i.Name,
			&i.Role,
			&i.SinceYear,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Bio,
			&i.HeadshotPath,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const restoreEnsembleMember = `-- name: RestoreEnsembleMember :exec
INSERT INTO ensemble_members (id, position, name, role, since_year, bio, created_at, updated_at)
VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7, ?7)
`

type RestoreEnsembleMemberParams struct {
	ID        int64
	Position  int64
	Name      string
	Role      string
	SinceYear string
	Bio       string
	Now       string
}

func (q *Queries) RestoreEnsembleMember(ctx context.Context, arg RestoreEnsembleMemberParams) error {
	_, err := q.db.ExecContext(ctx, restoreEnsembleMember,
		arg.ID,
		arg.Position,
		arg.Name,
		arg.Role,
		arg.SinceYear,
		arg.Bio,
		arg.Now,
	)
	return err
}

const updateEnsembleMember = `-- name: UpdateEnsembleMember :exec
UPDATE ensemble_members SET position = ?1, name = ?2, role = ?3, since_year = ?4, bio = ?5,
  updated_at = ?6
WHERE id = ?7
`

type UpdateEnsembleMemberParams struct {
	Position  int64
	Name      string
	Role      string
	SinceYear string
	Bio       string
	Now       string
	ID        int64
}

func (q *Queries) UpdateEnsembleMember(ctx context.Context, arg UpdateEnsembleMemberParams) error {
	_, err := q.db.ExecContext(ctx, updateEnsembleMember,
		arg.Position,
		arg.Name,
		arg.Role,
		arg.SinceYear,
		arg.Bio,
		arg.Now,
		arg.ID,
	)
	return err
}
