// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: site_settings.sql

package models

import (
	"context"
)

const createSiteSettings = `-- name: CreateSiteSettings :exec
INSERT INTO site_settings (id, collective_name, created_at, updated_at) VALUES (1, 'ESTHER PICTURES', ?1, ?1)
ON CONFLICT (id) DO NOTHING
`

func (q *Queries) CreateSiteSettings(ctx context.Context, now string) error {
	_, err := q.db.ExecContext(ctx, createSiteSettings, now)
	return err
}

const getSiteSettings = `-- name: GetSiteSettings :one
SELECT id, collective_name, tagline, hero_heading, contact_heading, email, studio_locations, instagram_url, letterboxd_url, footer_text, created_at, updated_at FROM site_settings WHERE id = 1
`

func (q *Queries) GetSiteSettings(ctx context.Context) (SiteSetting, error) {
	row := q.db.QueryRowContext(ctx, getSiteSettings)
	var i SiteSetting
	err := row.Scan(
		&i.ID,
		&i.CollectiveName,
		&i.Tagline,
		&i.HeroHeading,
		&i.ContactHeading,
		&i.Email,
		&i.StudioLocations,
		&i.InstagramUrl,
		&i.LetterboxdUrl,
		&i.FooterText,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateSiteSettings = `-- name: UpdateSiteSettings :exec
UPDATE site_settings SET collective_name = ?1, tagline = ?2, hero_heading = ?3,
  contact_heading = ?4, email = ?5, studio_locations = ?6,
  instagram_url = ?7, letterboxd_url = ?8, footer_text = ?9, updated_at = ?10
WHERE id = 1
`

type UpdateSiteSettingsParams struct {
	CollectiveName  string
	Tagline         string
	HeroHeading     string
	ContactHeading  string
	Email           string
	StudioLocations string
	InstagramUrl    string
	LetterboxdUrl   string
	FooterText      string
	Now             string
}

func (q *Queries) UpdateSiteSettings(ctx context.Context, arg UpdateSiteSettingsParams) error {
	_, err := q.db.ExecContext(ctx, updateSiteSettings,
		arg.CollectiveName,
		arg.Tagline,
		arg.HeroHeading,
		arg.ContactHeading,
		arg.Email,
		arg.StudioLocations,
		arg.InstagramUrl,
		arg.LetterboxdUrl,
		arg.FooterText,
		arg.Now,
	)
	return err
}
