// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package models

import (
	"database/sql"
	"time"
)

type ActiveStorageAttachment struct {
	ID         int64
	Name       string
	RecordType string
	RecordID   int64
	BlobID     int64
	CreatedAt  time.Time
}

type ActiveStorageBlob struct {
	ID          int64
	Key         string
	Filename    string
	ContentType sql.NullString
	Metadata    sql.NullString
	ServiceName string
	ByteSize    int64
	Checksum    sql.NullString
	CreatedAt   time.Time
}

type Clip struct {
	ID            int64
	Position      int64
	Title         string
	CreatedAt     string
	UpdatedAt     string
	VideoUrl      string
	ThumbnailPath string
	Runtime       string
	Format        string
	Years         string
	Status        string
}

type ContentVersion struct {
	ID        int64
	ItemType  string
	ItemID    int64
	Action    string
	Data      string
	UserID    sql.NullInt64
	CreatedAt string
}

type CraftService struct {
	ID          int64
	Position    int64
	Title       string
	Description string
	CreatedAt   string
	UpdatedAt   string
}

type EnsembleMember struct {
	ID           int64
	Position     int64
	Name         string
	Role         string
	SinceYear    string
	CreatedAt    string
	UpdatedAt    string
	Bio          string
	HeadshotPath string
}

type Session struct {
	ID          int64
	UserID      int64
	TokenDigest string
	IpAddress   string
	UserAgent   string
	CreatedAt   time.Time
	LastSeenAt  time.Time
}

type SiteSetting struct {
	ID              int64
	CollectiveName  string
	Tagline         string
	HeroHeading     string
	ContactHeading  string
	Email           string
	StudioLocations string
	InstagramUrl    string
	LetterboxdUrl   string
	FooterText      string
	CreatedAt       string
	UpdatedAt       string
}

type User struct {
	ID                 int64
	EmailAddress       string
	PasswordDigest     sql.NullString
	Role               string
	MustChangePassword int64
	CreatedAt          string
	UpdatedAt          string
}
