// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package models

import (
	"context"
	"database/sql"
)

const countUsers = `-- name: CountUsers :one
SELECT count(*) FROM users
`

func (q *Queries) CountUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (email_address, password_digest, role, must_change_password, created_at, updated_at)
VALUES (?1, ?2, ?3, ?4, ?5, ?5)
RETURNING id
`

type CreateUserParams struct {
	EmailAddress       string
	PasswordDigest     sql.NullString
	Role               string
	MustChangePassword int64
	Now                string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.EmailAddress,
		arg.PasswordDigest,
		arg.Role,
		arg.MustChangePassword,
		arg.Now,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users WHERE id = ?
`

func (q *Queries) DeleteUser(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteUser, id)
	return err
}

const getUser = `-- name: GetUser :one
SELECT id, email_address, role, must_change_password FROM users WHERE id = ?
`

type GetUserRow struct {
	ID                 int64
	EmailAddress       string
	Role               string
	MustChangePassword int64
}

func (q *Queries) GetUser(ctx context.Context, id int64) (GetUserRow, error) {
	row := q.db.QueryRowContext(ctx, getUser, id)
	var i GetUserRow
	err := row.Scan(
		&i.ID,
		&i.EmailAddress,
		&i.Role,
		&i.MustChangePassword,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, email_address, role, must_change_password FROM users ORDER BY role, email_address
`

type ListUsersRow struct {
	ID                 int64
	EmailAddress       string
	Role               string
	MustChangePassword int64
}

func (q *Queries) ListUsers(ctx context.Context) ([]ListUsersRow, error) {
	rows, err := q.db.QueryContext(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUsersRow{}
	for rows.Next() {
		var i ListUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.EmailAddress,
			&i.Role,
			&i.MustChangePassword,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setMustChangePassword = `-- name: SetMustChangePassword :exec
UPDATE users SET must_change_password = ?1, updated_at = ?2 WHERE id = ?3
`

type SetMustChangePasswordParams struct {
	MustChangePassword int64
	Now                string
	ID                 int64
}

func (q *Queries) SetMustChangePassword(ctx context.Context, arg SetMustChangePasswordParams) error {
	_, err := q.db.ExecContext(ctx, setMustChangePassword, arg.MustChangePassword, arg.Now, arg.ID)
	return err
}
